set nocompatible
syntax on
filetype plugin indent on	       "Filetype detection and indent enabled

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'rafi/awesome-vim-colorschemes'

Plugin 'Yggdroot/indentLine'

Plugin 'preservim/nerdtree'

Plugin 'octol/vim-cpp-enhanced-highlight'

Plugin 'jiangmiao/auto-pairs'

Plugin 'vim-airline/vim-airline'

Plugin 'vim-airline/vim-airline-themes'

Plugin 'airblade/vim-gitgutter'

Plugin 'ycm-core/YouCompleteMe'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

colorscheme apprentice

" -----------------------------------------------------------config for ctags
set tags=$HOME/.vim/tags/tags

"--------------------------------------------------------------config for ycm
let g:ycm_clangd_binary_path = "/usr/bin/clangd-11"
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_max_diagnostics_to_display = 0
""TO DISABLE YCM
""let g:loaded_youcompleteme = 1

"--------------------------------------------------------To detect cuda files
autocmd BufNewFile,BufRead *.cu set filetype=cpp

"-------------------------------------------------------config for indentLine
let g:indentLine_color_term = 240
let g:indentLine_char = '┆'

"---------------------------------------------------------config for nerdtree
autocmd vimenter * NERDTree
autocmd VimEnter * wincmd p
"Close VIM if nerdtree is the only window left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"---------------------------------------------------------config for easytags
"let g:easytags_async = 1	    " update ctags asynchronusly

"----------------------------------------------config for c++ syntax coloring
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_scope_highlight = 1
let g:cpp_no_function_highlight = 1

"-------------------------------------------------------config for auto-pairs
let g:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`'}

" General
set path+=**		" Append to path for fuzzy finding
set wildmenu		" Wildmenu for fuzzy finding
set number		" Show line numbers
set linebreak		" Break lines at word (requires Wrap lines)
set textwidth=80	" Line wrap (number of cols)
set showmatch		" Highlight matching brace

set hlsearch		" Highlight all search results
set ignorecase		" Always case-insensitive
set incsearch		" Searches for strings incrementally

set autoindent		" Auto-indent new lines
set cindent		" Use 'C' style program indenting
set shiftwidth=2	" Number of auto-indent spaces
set smartindent		" Enable smart-indent
set smarttab		" Enable smart-tabs
set softtabstop=2	" Number of spaces per Tab
set updatetime=100	" Update early for gitGutter
set shortmess-=S
set showcmd
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
set mouse=a
" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

" For selecting text between blocks in visual mode.
noremap % v%

" for copying and pasting
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p

" Advanced
set ruler			" Show row and column ruler information
set backspace=indent,eol,start	" Backspace behaviour
